# Generated by Django 5.2.5 on 2026-06-18 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('phone', models.IntegerField(blank=True)),
                ('country', models.CharField(blank=True, max_length=255)),
                ('plan', models.CharField(choices=[('Free', 'Free'), ('Premium', 'Premium')], default='Free')),
                ('profile_image', models.ImageField(blank=True, upload_to='profile-images/')),
                ('is_active', models.BooleanField(default=0)),
                ('is_staff', models.BooleanField(default=0)),
                ('is_superuser', models.BooleanField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
