# Generated by Django 5.2.5 on 2026-06-18 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_chat_messages_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messages_table',
            new_name='MessagesTable',
        ),
    ]
