# Generated by Django 5.2.5 on 2026-06-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_messages_table_messagestable'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='messagestable',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
