# Generated by Django 5.2.5 on 2026-06-19 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_chat_created_at_messagestable_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagestable',
            old_name='msg',
            new_name='content',
        ),
    ]
