# Generated by Django 5.2.5 on 2026-09-21 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_msg_messagestable_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='deltion_flag',
            field=models.BooleanField(default=0),
        ),
    ]
