# Generated by Django 5.2.5 on 2026-09-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_chat_deltion_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='chat_pinned',
            field=models.BooleanField(default=0),
        ),
    ]
