# Generated by Django 5.2.5 on 2026-09-27 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_chat_chat_pinned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='chat_pinned',
            new_name='is_deleted',
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='deltion_flag',
            new_name='is_pinned',
        ),
    ]
